import { PASSWORD_MIN_LENGTH } from "../auth/password-vars.model";
import { metaTagDefaults } from "../meta/metatags.model";
import { PublicIconPaths } from "../routes-and-paths/icon-paths.model";

export enum GlobalFieldValues {
  ABOUT_US = 'About Us',
  ADMIN = `Admin`,
  ADMIN_LOGIN = `Admin Login`,
  ACCOUNT = `Account`,
  AUTH_PROCESSING = `Authentication in progress, please wait...`,
  BLOG = `Blog`,
  CANCEL = `Cancel`,
  CHANGE_PASSWORD = `Change Password`,
  CHANGE_PASSWORD_BLURB = `A password reset email will be sent to`,
  CHECK_INBOX = `Check your inbox for an email to reset your password.`,
  CLOSE = `Close`,
  CONFIRM = `Confirm`,
  CONFIRMING_EMAIL = `Processing your email, please wait...`,
  CONTACT = `Contact`,
  CONTACT_FORM = `Contact Form`,
  CONTENT = `Content`,
  CREATE_POST = `Create Post`,
  DELETE = `Delete`,
  DELETE_POST_CONF_BODY = `Are you sure you'd like to delete this post? This action cannont be undone`,
  DELETE_POST_CONF_TITLE = `Delete Post`,
  DISCARD_EDITS_TITLE = `Discard Edits`,
  DISCARD_EDITS_BODY = `Are you sure you want to leave? All changes will be discarded.`,
  DISPLAY_NAME = `Display Name`,
  DRAFTS = `Drafts`,
  EDIT = `Edit`,
  EDIT_NAME = `Edit Name`,
  EDIT_POST = `Edit Post`,
  EDIT_POST_BOILERPLATE = `Edit Post Boilerplate`,
  EMAIL = `Email`,
  EMAIL_CONFIRMED = `Success! Your email has been confirmed.`,
  FIRST_NAME = `First Name`,
  FORGOT_PASSWORD = `Forgot password?`,
  FREE_LESSONS = `Free Lessons`,
  GET_IN_TOUCH = `Get In Touch`,
  HOME = `Home`,
  HOUR = `Hour`,
  JOIN_COMMUNITY = `Join Community`,
  LEARN_MORE = `Learn More`,
  LOGIN = `Login`,
  LOGOUT = `Logout`,
  MESSAGE = `Message`,
  MINS = `Mins`,
  MODIFIED_BY = `Modified by`,
  NO = `No`,
  NO_THANKS = `No, thanks`,
  OPT_IN_BLURB = `Yes, I'd love to receive a weekly newsletter with the latest content from`,
  PASSWORD = `Password`,
  PASSWORD_HINT = `Must be at least ${PASSWORD_MIN_LENGTH} characters`,
  PODCAST = `Podcast`,
  PODCAST_EPISODE_URL = `Podcast Episode Url`,
  POST_DESCRIPTION = `Post Description`,
  POST_KEYWORDS = `Post Keywords`,
  POST_TITLE = `Post Title`,
  PUBLISH = `Publish`,
  PUBLISHED = `Published`,
  READ_MORE = `Read More`,
  REQUEST_PROCESSING = `Request processing`,
  RESET_PASSWORD = `Reset Password`,
  SAVE = `Save`,
  SCHEDULE_POST = `Schedule Post`,
  SCHEDULE_POST_BLURB = `Post will be published on`,
  SEE_MORE = `See More`,
  SELECT_DATE = `Select Date`,
  SIGN_IN_WITH_EMAIL = `Sign In with Email`,
  SUBMIT = `Submit`,
  SUBSCRIBERS = `Subscribers`,
  UNPUBLISH = `Unpublish`,
  UNPUBLISHED = `Unpublished`,
  UNSCHEDULE = `Unschedule`,
  UPLOAD_IMAGE = `Upload Image`,
  VERIFICATION_FAILED = `Failed to process your email. If you continue to receive this message, try resubmitting your request. If all else fails, contact `,
  VIEW_COLLECTION = `View Collection`,
  VIEW_FULL_PODCAST = `View Full Podcast`,
  VIEW_MORE_POSTS = `View More Posts`,
  VIEW_POST = `View Post`,
  VIDEO_URL = `Video Url`,
  YES = `Yes`,
}

export const SiteSpecificFieldValues = {
  expnPublic: {
    aboutPageTitle: `Welcome to ${metaTagDefaults.expnPublic.metaTagSiteName}!`,
    aboutPageBlurbPartOne: `${metaTagDefaults.expnPublic.metaTagSiteName} is an online platform for developing social skills and mental fortitude.`,
    aboutPageBlurbPartTwo: `Mary Daphne and Greg combine decades of experience to offer a unique approach to building stronger social connections.`,
    aboutMetaTitle: `About Us - ${metaTagDefaults.expnPublic.metaTagSiteName}`,
    aboutMetaDescription: `Stronger social connections are at the core of who we are. Our job is to supercharge your social interactions with your friends, colleagues, and clients using our research-backed techniques.`,
    aboutBodyVideoUrl: `https://youtu.be/_onRdMrhzmw`,
    blogMetaTitle: `Blog - ${metaTagDefaults.expnPublic.metaTagSiteName}`,
    blogMetaDescription: `On ${metaTagDefaults.expnPublic.metaTagSiteName}'s blog you have access to our complete library of free lessons on building stronger social connections. From confident communication, to building rapport, to asserting yourself in public, our goal is to supercharge your social interactions with your friends, colleagues, and clients.`,
    blogPageTitle: `${metaTagDefaults.expnPublic.metaTagSiteName} Blog`,
    blogPageHeroSubtitle: `Access our complete library of free lessons on building stronger social connections`,
    blogActionMessage: `View Collection`,
    contactMetaTitle: `Contact Us - ${metaTagDefaults.expnPublic.metaTagSiteName}`,
    contactMetaDescription: `Get in touch with the ${metaTagDefaults.expnPublic.metaTagSiteName} team using this contact form. We welcome questions, suggestions, and any thoughtful input. Let us know if there is anything else we can do to help you strengthen your social connections!`,
    contactPageTitle: 'Contact Us',
    contactPageHeroSubtitle: 'Questions, suggestions, and thoughtful input are welcome',
    contactActionMessage: 'Get in Touch',
    homeCapTitleOne: 'Confidence',
    homeCapBodyOne: 'Cultivate your mental fortitude for stronger social connections with the people who matter most',
    homeCapIconOnePath: PublicIconPaths.FIST_ICON,
    homeCapTitleTwo: 'Authenticity',
    homeCapBodyTwo: 'Project your unique and authentic self to win the trust of your friends, colleagues, and clients',
    homeCapIconTwoPath: PublicIconPaths.SHIELD_ICON,
    homeCapTitleThree: 'Poise',
    homeCapBodyThree: 'Assert yourself in public and communicate with clarity and grace in any social context',
    homeCapIconThreePath: PublicIconPaths.LOTUS_FLOWER_ICON,
    homePageTitle: 'A Richer Life Begins with Stronger Social Connections',
    homeActionMessage: 'Learn More',
    privacyPolicyMetaDescription: `We take privacy seriously. This page contains how we collect data and how we use that data.`,
    privacyPolicyMetaTitle: `Privacy Policy - ${metaTagDefaults.expnPublic.metaTagSiteName}`,
    termsAndConditionsMetaDescription: `When you use this website we ask that you kindly abide by the below Terms and Conditions`,
    termsAndConditionsMetaTitle: `Terms and Conditions - ${metaTagDefaults.expnPublic.metaTagSiteName}`,
    podcastMetaTitle: `Podcast - ${metaTagDefaults.expnPublic.metaTagSiteName}`,
    podcastMetaDescription: `Get our lastest social skills strategies in audio form from our weekly ${metaTagDefaults.expnPublic.metaTagSiteName} podcast. Available on all the major directories, including Soundlcoud, iTunes, Google Podcast, Spotify, and more.`,
    podcastPageTitle: 'Podcast',
    podcastPageHeroSubtitle: 'Get our lastest social skills strategies in audio form',
    podcastActionMessage: 'View Episodes',
    productListMetaTitle: `Products - ${metaTagDefaults.expnPublic.metaTagSiteName}`,
    productListMetaDescription: `${metaTagDefaults.expnPublic.metaTagSiteName} offers a variety of products to help you improve your social skills and professional interactions. From communications coaching to detailed web courses, our goal is to make you the best communicator you can be.`,
    purchaseConfirmationMetaTitle: `Purchase Confirmation - ${metaTagDefaults.expnPublic.metaTagSiteName}`,
    serviceListMetaTitle: `Services - ${metaTagDefaults.expnPublic.metaTagSiteName}`,
    serviceListMetaDescription: `${metaTagDefaults.expnPublic.metaTagSiteName} offers a variety of services to help you improve your social skills and professional interactions. From communications coaching to detailed web courses, our goal is to make you the best communicator you can be.`,
    webcourseListMetaTitle: `Web Courses - ${metaTagDefaults.expnPublic.metaTagSiteName}`,
    webcourseListMetaDescription: `${metaTagDefaults.expnPublic.metaTagSiteName} offers interactive, in-depth web courses that are designed to take your social skills and professional communications to a new level.`,
    downloadPromoTitle: `Afraid of Small Talk?`,
    downloadPromoDescription: `Sign up to get our five foolproof strategies for mastering small talk.`,
    downloadPromoDeclineButton: `Nah, I'm already a small talk pro.`,
    subscribeBoxTitle: `Don't miss out`,
    subscribeBoxSubtitle: `Sign up for the latest communication techniques and special offers.`,
    waitListBoxDescription: `Sign up for early bird prices on this webcourse along with our latest communication techniques.`,
  },
  mdlsPublic: {
    aboutPageTitle: `Welcome to ${metaTagDefaults.mdlsPublic.metaTagSiteName}!`,
    aboutPageBlurbPartOne: `${metaTagDefaults.mdlsPublic.metaTagSiteName} is a community of health-obsessed lifesteyle optimizers.`,
    aboutPageBlurbPartTwo: `Mary Daphne brings combines a passion for fitness and the latest health-centric research for a longer, healthier life.`,
    aboutMetaTitle: `About Us - ${metaTagDefaults.mdlsPublic.metaTagSiteName}`,
    aboutMetaDescription: `Our mission at ${metaTagDefaults.mdlsPublic.metaTagSiteName} is to expand your sense of opportunity and possibility.`,
    aboutBodyVideoUrl: `https://youtu.be/X949bB9fqMA`,
    blogMetaTitle: `Blog - ${metaTagDefaults.mdlsPublic.metaTagSiteName}`,
    blogMetaDescription: `On ${metaTagDefaults.mdlsPublic.metaTagSiteName}'s blog you have access to our complete library of insights and personal development content.`,
    blogPageTitle: `Our Blog`,
    blogPageHeroSubtitle: `Access our complete library of insights and personal development content`,
    blogActionMessage: `View Collection`,
    contactMetaTitle: `Contact Us - ${metaTagDefaults.mdlsPublic.metaTagSiteName}`,
    contactMetaDescription: `Get in touch with the ${metaTagDefaults.mdlsPublic.metaTagSiteName} team using this contact form. We welcome questions, suggestions, and any thoughtful input.`,
    contactPageTitle: 'Contact Us',
    contactPageHeroSubtitle: 'Questions, suggestions, and thoughtful input are welcome',
    contactActionMessage: 'Get in Touch',
    homeCapTitleOne: 'Strength',
    homeCapBodyOne: 'Project confidence and poise by leveraging skills and expertise you have built from the ground up',
    homeCapIconOnePath: PublicIconPaths.FIST_ICON,
    homeCapTitleTwo: 'Authority',
    homeCapBodyTwo: 'Develop a deeper understanding of yourself and how people see you to win the trust of your peers and clients',
    homeCapIconTwoPath: PublicIconPaths.SHIELD_ICON,
    homeCapTitleThree: 'Intuition',
    homeCapBodyThree: 'Deploy battle-tested strategies to overcome challenges and obstacles in unfamiliar contexts',
    homeCapIconThreePath: PublicIconPaths.LOTUS_FLOWER_ICON,
    homePageTitle: 'Expand your sense of possibility and opportunity',
    homeActionMessage: 'Learn More',
    privacyPolicyMetaDescription: `We take privacy seriously. This page contains how we collect data and how we use that data.`,
    privacyPolicyMetaTitle: `Privacy Policy - ${metaTagDefaults.mdlsPublic.metaTagSiteName}`,
    termsAndConditionsMetaDescription: `When you use this website we ask that you kindly abide by the below Terms and Conditions`,
    termsAndConditionsMetaTitle: `Terms and Conditions - ${metaTagDefaults.mdlsPublic.metaTagSiteName}`,
    podcastMetaTitle: `Podcast - ${metaTagDefaults.mdlsPublic.metaTagSiteName}`,
    podcastMetaDescription: `Get our lastest health and fitness strategies and content in audio form from our weekly ${metaTagDefaults.mdlsPublic.metaTagSiteName} podcast. Available on all the major directories, including Soundlcoud, iTunes, Google Podcast, Spotify, and more.`,
    podcastPageTitle: 'Podcast',
    podcastPageHeroSubtitle: 'Get our lastest health and fitness strategies and content in audio form',
    podcastActionMessage: 'View Episodes',
    productListMetaTitle: `Products - ${metaTagDefaults.mdlsPublic.metaTagSiteName}`,
    productListMetaDescription: `${metaTagDefaults.mdlsPublic.metaTagSiteName} offers a variety of services to help you improve your confidence, health, and decision making. From life coaching to high quality web courses, our goal is to equip you for when opportunity comes knocking.`,
    purchaseConfirmationMetaTitle: `Purchase Confirmation - ${metaTagDefaults.mdlsPublic.metaTagSiteName}`,
    serviceListMetaTitle: `Services - ${metaTagDefaults.mdlsPublic.metaTagSiteName}`,
    serviceListMetaDescription: `${metaTagDefaults.mdlsPublic.metaTagSiteName} offers a variety of services to help you improve your confidence, health, and decision making. From life coaching to high quality web courses, our goal is to equip you for when opportunity comes knocking.`,
    webcourseListMetaTitle: `Web Courses - ${metaTagDefaults.mdlsPublic.metaTagSiteName}`,
    webcourseListMetaDescription: `${metaTagDefaults.mdlsPublic.metaTagSiteName} offers a variety of services to help you improve your confidence, health, and decision making. From life coaching to high quality web courses, our goal is to equip you for when opportunity comes knocking.`,
    downloadPromoTitle: `Afraid of Small Talk?`,
    downloadPromoDescription: `Sign up to get our five foolproof strategies for mastering small talk.`,
    downloadPromoDeclineButton: `Nah, I'm already a small talk pro.`,
    subscribeBoxTitle: `Don't miss out`,
    subscribeBoxSubtitle: `Sign up for my latest content releases and special offers.`,
    waitListBoxDescription: `Sign up for early bird prices on this webcourse along with our latest content releases.`,
  },
  sywPublic: {
    aboutPageTitle: `Welcome to ${metaTagDefaults.sywPublic.metaTagSiteName}!`,
    aboutPageBlurbPartOne: `For years, I was obsessed with achieving financial freedom. Once I got there, I became obsessed with equipping others to do the same.`,
    aboutPageBlurbPartTwo: `With an MBA from the Wharton School of Business, I have a solid grasp of the fundamentals. But as you'll learn below, my wealth building journey wasn't as clear cut as it sounds.`,
    aboutMetaTitle: `About Us - ${metaTagDefaults.sywPublic.metaTagSiteName}`,
    aboutMetaDescription: `There’s a lot of wealth out there. But no one’s going to hand it to you. If you want your piece of the pie, you need to go out and get it. Stake Your Wealth is here to help you do that. We dig into topics ranging from personal finance, to financial independence, to investing in, and building, profitable businesses.`,
    aboutBodyVideoUrl: `https://youtu.be/YQz4bULPVHM`,
    blogMetaTitle: `Blog - ${metaTagDefaults.sywPublic.metaTagSiteName}`,
    blogMetaDescription: `On ${metaTagDefaults.sywPublic.metaTagSiteName}'s blog you have access to our complete library of free lessons on building wealth. We dig into topics ranging from personal finance, to financial independence, to investing in, and building, profitable businesses.`,
    blogPageTitle: `${metaTagDefaults.sywPublic.metaTagSiteName} Blog`,
    blogPageHeroSubtitle: `Access to our complete library of free lessons on building wealth`,
    blogActionMessage: `View Collection`,
    contactMetaTitle: `Contact Us - ${metaTagDefaults.sywPublic.metaTagSiteName}`,
    contactMetaDescription: `Get in touch with the ${metaTagDefaults.sywPublic.metaTagSiteName} team using this contact form. We welcome questions, suggestions, and any thoughtful input. Let us know if there is anything else we can do to help you on your wealth building journey!`,
    contactPageTitle: 'Contact Us',
    contactPageHeroSubtitle: 'Questions, suggestions, and thoughtful input are welcome',
    contactActionMessage: 'Get in Touch',
    homeCapTitleOne: 'Empowerment',
    homeCapBodyOne: `Equip yourself to build the wealth you deserve by leveraging your unique skills and assets`,
    homeCapIconOnePath: PublicIconPaths.SHIELD_ICON,
    homeCapTitleTwo: 'Control',
    homeCapBodyTwo: `Build an unshakable foundation of expertise in managing your cash flow and personal finances`,
    homeCapIconTwoPath: PublicIconPaths.FIST_ICON,
    homeCapTitleThree: 'Liberation',
    homeCapBodyThree: `Free yourself from society's outdated definitions of financial independence and financial security`,
    homeCapIconThreePath: PublicIconPaths.LOTUS_FLOWER_ICON,
    homePageTitle: 'Simple, common sense strategies for building wealth',
    homeActionMessage: 'Learn More',
    privacyPolicyMetaDescription: `We take privacy seriously. This page contains how we collect data and how we use that data.`,
    privacyPolicyMetaTitle: `Privacy Policy - ${metaTagDefaults.sywPublic.metaTagSiteName}`,
    termsAndConditionsMetaDescription: `When you use this website we ask that you kindly abide by the below Terms and Conditions`,
    termsAndConditionsMetaTitle: `Terms and Conditions - ${metaTagDefaults.sywPublic.metaTagSiteName}`,
    podcastMetaTitle: `Podcast - ${metaTagDefaults.sywPublic.metaTagSiteName}`,
    podcastMetaDescription: `Get our lastest wealth building strategies in audio form from our weekly ${metaTagDefaults.sywPublic.metaTagSiteName} podcast. Available on all the major directories, including Soundlcoud, iTunes, Google Podcast, Spotify, and more.`,
    podcastPageTitle: 'Podcast',
    podcastPageHeroSubtitle: 'Get our lastest wealth building strategies in audio form',
    podcastActionMessage: 'View Episodes',
    productListMetaTitle: `Products - ${metaTagDefaults.sywPublic.metaTagSiteName}`,
    productListMetaDescription: `${metaTagDefaults.sywPublic.metaTagSiteName} offers a variety of products to help you improve your wealth building skills. From personal finance, to financial independence, to investing in, and building, profitable businesses, our goal is to equip you to build the wealth you deserve.`,
    purchaseConfirmationMetaTitle: `Purchase Confirmation - ${metaTagDefaults.sywPublic.metaTagSiteName}`,
    serviceListMetaTitle: `Services - ${metaTagDefaults.sywPublic.metaTagSiteName}`,
    serviceListMetaDescription: `${metaTagDefaults.sywPublic.metaTagSiteName} offers a variety of products to help you improve your wealth building skills. From personal finance, to financial independence, to investing in, and building, profitable businesses, our goal is to equip you to build the wealth you deserve.`,
    webcourseListMetaTitle: `Web Courses - ${metaTagDefaults.sywPublic.metaTagSiteName}`,
    webcourseListMetaDescription: `${metaTagDefaults.sywPublic.metaTagSiteName} offers a variety of products to help you improve your wealth building skills. From personal finance, to financial independence, to investing in, and building, profitable businesses, our goal is to equip you to build the wealth you deserve.`,
    downloadPromoTitle: `Is Building Wealth a Priority For You?`,
    downloadPromoDescription: `Get started with our free 3-Step Guide to increasing your net worth.`,
    downloadPromoDeclineButton: `Nah, I'm already a wealth building pro.`,
    subscribeBoxTitle: `Don't miss out`,
    subscribeBoxSubtitle: `Sign up to get our 3-Step Guide to building wealth.`,
    waitListBoxDescription: `Sign up for early bird prices on this webcourse along with our latest wealth building strategies.`,
  },
  advePublic: {
    aboutPageTitle: `Welcome to ${metaTagDefaults.advePublic.metaTagSiteName}!`,
    aboutPageBlurbPartOne: `At ${metaTagDefaults.advePublic.metaTagSiteName}, we teach you to speak English fluently and confidently through real-world English conversations and role-play scenarios.`,
    aboutPageBlurbPartTwo: `Mary Daphne and Greg combine decades of linguistic expertise and international experience to offer a unique approach to English fluency.`,
    aboutMetaTitle: `About Us - ${metaTagDefaults.advePublic.metaTagSiteName}`,
    aboutMetaDescription: `Our mission at Advanced English is to teach you to speak English fluently and confidently. At Advanced English, we teach English fluency by immersing our students in real-world English conversations and scenarios. Alongside the language, we teach American English culture and norms.`,
    aboutBodyVideoUrl: `https://youtu.be/4YWtm8T8gj8`,
    blogMetaTitle: `Blog - ${metaTagDefaults.advePublic.metaTagSiteName}`,
    blogMetaDescription: `On ${metaTagDefaults.advePublic.metaTagSiteName}'s blog you have access to our complete library of free lessons on advanced english. Our goal with our content is for you to learn to speak English fluently and confidently.`,
    blogPageTitle: `${metaTagDefaults.advePublic.metaTagSiteName} Blog`,
    blogPageHeroSubtitle: `Access our complete library of free lessons on speaking English fluently and confidently`,
    blogActionMessage: `View Collection`,
    contactMetaTitle: `Contact Us - ${metaTagDefaults.advePublic.metaTagSiteName}`,
    contactMetaDescription: `Get in touch with the ${metaTagDefaults.advePublic.metaTagSiteName} team using this contact form. We welcome questions, suggestions, and any thoughtful input. Let us know if there is anything else we can do to help you on your English learning journey!`,
    contactPageTitle: 'Contact Us',
    contactPageHeroSubtitle: 'Questions, suggestions, and thoughtful input are welcome',
    contactActionMessage: 'Get in Touch',
    homeCapTitleOne: 'Fluency',
    homeCapBodyOne: `Communicate like a native English speaker in any professional or social context`,
    homeCapIconOnePath: PublicIconPaths.SHIELD_ICON,
    homeCapTitleTwo: 'Confidence',
    homeCapBodyTwo: `Feel confident in your English interactions by understanding American English culture and norms`,
    homeCapIconTwoPath: PublicIconPaths.FIST_ICON,
    homeCapTitleThree: 'Clarity',
    homeCapBodyThree: `Learn to speak in clear, concise English to ensure your voice is heard and understood`,
    homeCapIconThreePath: PublicIconPaths.LOTUS_FLOWER_ICON,
    homePageTitle: 'Learn to speak English fluently and confidently',
    homeActionMessage: 'Learn More',
    privacyPolicyMetaDescription: `We take privacy seriously. This page contains how we collect data and how we use that data.`,
    privacyPolicyMetaTitle: `Privacy Policy - ${metaTagDefaults.advePublic.metaTagSiteName}`,
    termsAndConditionsMetaDescription: `When you use this website we ask that you kindly abide by the below Terms and Conditions`,
    termsAndConditionsMetaTitle: `Terms and Conditions - ${metaTagDefaults.advePublic.metaTagSiteName}`,
    podcastMetaTitle: `Podcast - ${metaTagDefaults.advePublic.metaTagSiteName}`,
    podcastMetaDescription: `Get our lastest advanced English strategies in audio form from our weekly ${metaTagDefaults.advePublic.metaTagSiteName} podcast. Available on all the major directories, including Soundlcoud, iTunes, Google Podcast, Spotify, and more.`,
    podcastPageTitle: 'Podcast',
    podcastPageHeroSubtitle: 'Get our lastest wealth building strategies in audio form',
    podcastActionMessage: 'View Episodes',
    productListMetaTitle: `Products - ${metaTagDefaults.advePublic.metaTagSiteName}`,
    productListMetaDescription: `${metaTagDefaults.advePublic.metaTagSiteName} offers a variety of products to help you improve your advanced English fluency. From conversational English, to business English, to native-sounding English, our goal is to equip you to speak English with fluency and confidence.`,
    purchaseConfirmationMetaTitle: `Purchase Confirmation - ${metaTagDefaults.advePublic.metaTagSiteName}`,
    serviceListMetaTitle: `Services - ${metaTagDefaults.advePublic.metaTagSiteName}`,
    serviceListMetaDescription: `${metaTagDefaults.advePublic.metaTagSiteName} offers a variety of products to help you improve your advanced English fluency. From conversational English, to business English, to native-sounding English, our goal is to equip you to speak English with fluency and confidence.`,
    webcourseListMetaTitle: `Web Courses - ${metaTagDefaults.advePublic.metaTagSiteName}`,
    webcourseListMetaDescription: `${metaTagDefaults.advePublic.metaTagSiteName} offers a variety of products to help you improve your advanced English fluency. From conversational English, to business English, to native-sounding English, our goal is to equip you to speak English with fluency and confidence.`,
    downloadPromoTitle: `Want to Speak English Fluently?`,
    downloadPromoDescription: `Get started with our free Small Talk Guide.`,
    downloadPromoDeclineButton: `Nah, I'm already a small-talk pro.`,
    subscribeBoxTitle: `Don't miss out`,
    subscribeBoxSubtitle: `Sign up to get our free Small Talk Guide.`,
    waitListBoxDescription: `Sign up for early bird prices on this webcourse along with our latest Advanced English strategies.`,
  },
};